packadd! dracula

syntax enable
let g:dracula_colorterm=0
colorscheme dracula
set t_Co=256
set termguicolors

" disable compatibility with vi which can cause unexpected issues
set nocompatible

" enable type file detection
filetype on

" enable plugins and load plugin for the detected file type
filetype plugin on

" load an indent file for the detected file type
filetype indent on

" enable auto completion menu after pressing tab
set wildmenu

" wildmenu ignore list
set wildignore=*.docx,*.xlsx,*.jpg,*.png,*.gif,*.pdf,*.exe,*.img

" limit textwidth to 80
set textwidth=79

" show numbers 
set number
set numberwidth=4

" show where my cursor is
set cursorline

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent
set smartindent
set smarttab

" search options
set hlsearch
set incsearch

set showmatch

" encoding options
set encoding=utf8
