# -----------------------------------------------
# Bindings
# -----------------------------------------------

# Prefix
unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

# Reload
unbind r
bind r source-file ~/.tmux.conf \; display "tmux configuration reloaded!"

# Window Title
set-window-option -g automatic-rename on
set-option -g set-titles on

# -----------------------------------------------
# Settings
# -----------------------------------------------

# 256-color
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# -----------------------------------------------
# Statusbar
# -----------------------------------------------

set-option -g status "on"

# Default statusbar colors
set-option -g status-style bg=#073642,fg=#fdf6e3

# Left statusbar > sessions
set-option -g status-left "#[bg=#93a1a1,fg=#fdf6e3,bold] ❐ #S #[bg=#657b83,fg=#93a1a1]#[bg=#073642,fg=#657b83]"

# Left statusbar > windows > separator
set-window-option -g window-status-separator ""

# Left statusbar > windows
set-window-option -g window-status-format "\
#[bg=#002b36,fg=#073642,none]\
#[bg=#002b36,fg=#586e75,none] #I* \
#[bg=#002b36,fg=#073642,none] \
#[bg=#002b36,fg=#586e75,none]#W \
#[bg=#002b36,fg=#073642,none] \
#[bg=#073642,fg=#002b36,none]"

# Left statusbar > windows > current
set-window-option -g window-status-current-format "\
#[bg=#93a1a1,fg=#073642,none]\
#[bg=#93a1a1,fg=#fdf6e3,none] #I* \
#[bg=#93a1a1,fg=#657b83,none] \
#[bg=#93a1a1,fg=#fdf6e3,bold]#W \
#[bg=#657b83,fg=#93a1a1]\
#[bg=#073642,fg=#657b83]"

# Right statusbar
set-option -g status-right "\
#[bg=#073642,fg=#586e75,none] tmux \
#[bg=#073642,fg=#586e75,none]\
#[bg=#586e75,fg=#fdf6e3,none] %D \
#[bg=#586e75,fg=#93a1a1,none]\
#[bg=#93a1a1,fg=#fdf6e3,none] %H:%M "
