# -----------------------------------------------
# Bindings
# -----------------------------------------------

# Prefix
unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

# Reload
unbind r
bind r source-file ~/.tmux.conf \; display "tmux configuration reloaded!"

# Pane Switching
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# -----------------------------------------------
# Settings
# -----------------------------------------------

# Repeat Time
set-option -g repeat-time 0

# Window Title
set-window-option -g automatic-rename on
set-option -g set-titles on

# 256-color
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# -----------------------------------------------
# Statusbar
# -----------------------------------------------

# Statusbar / enable/disable
set-option -g status "on"

# Statusbar > Default
set-option -g status-style bg=#073642,fg=#fdf6e3

# Statusbar > Left > Sessions
set-option -g status-left "#[bg=#93a1a1,fg=#fdf6e3,bold] ❐ #S #[bg=#657b83,fg=#93a1a1]#[bg=#073642,fg=#657b83]"

# Statusbar > Left > Windows
set-window-option -g window-status-format "\
#[bg=#002b36,fg=#073642,none]\
#[bg=#002b36,fg=#586e75,none] #I* \
#[bg=#002b36,fg=#073642,none] \
#[bg=#002b36,fg=#586e75,none]#W \
#[bg=#002b36,fg=#073642,none] \
#[bg=#073642,fg=#002b36,none]"

# Statusbar > Left > Windows > Current
set-window-option -g window-status-current-format "\
#[bg=#93a1a1,fg=#073642,none]\
#[bg=#93a1a1,fg=#fdf6e3,none] #I* \
#[bg=#93a1a1,fg=#657b83,none] \
#[bg=#93a1a1,fg=#fdf6e3,bold]#W \
#[bg=#657b83,fg=#93a1a1]\
#[bg=#073642,fg=#657b83]"

# Statusbar > Left > Windows > Separator
set-window-option -g window-status-separator ""

# Statusbar > Right
set-option -g status-right "\
#[bg=#073642,fg=#586e75,none] tmux \
#[bg=#073642,fg=#586e75,none]\
#[bg=#586e75,fg=#fdf6e3,none] %D \
#[bg=#586e75,fg=#93a1a1,none]\
#[bg=#93a1a1,fg=#fdf6e3,none] %H:%M "
