# -----------------------------------------------
# Bindings
# -----------------------------------------------

# Prefix
unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

# Reload
unbind r
bind r source-file ~/.tmux.conf \; display "tmux configuration reloaded!"

# Window Title
set-window-option -g automatic-rename on
set-option -g set-titles on

# -----------------------------------------------
# Settings
# -----------------------------------------------

# 256-color
set -g default-terminal "tmux-256color"
