# keybinds
bind r source-file ~/.tmux.conf \; display-message "tmux configuration reloaded!"

# default is C-b, but vim uses C-b
set-option -g prefix C-a

# tmux plugin manager
run -b '~/.tmux/plugins/tpm/tpm'

# plugins
set -g @plugin 'dracula/tmux'
set -g @dracula-show-left-icon hostname
set -g @dracula-plugins "cpu-usage ram-usage time"
